---
title: "Penguin Body Mass by Species"
author: "Nitpreet Bamra"
date: "2026-09-22"
---

## Data Disclosure

The data from this analysis is from the palmerpenguins dataset. This dataset is a standard python dataset and can be found at the following link : 
[https://allisonhorst.github.io/palmerpenguins/](https://allisonhorst.github.io/palmerpenguins/) . This dataset is by  by Dr. Kristen Gorman and the Palmer Station, Antarctica LTER, a member of the Long Term Ecological Research Network and gives information about penguins. 

The goal of this analysis is to compare body masss of the penguins across the different penguin species 


```{python}
#| warning: false

from palmerpenguins import load_penguins
import pandas as pd
import matplotlib.pyplot as plt

penguins = load_penguins()
penguins.head()

```


## Data Exploration

unique species

```{python}
#| warning: false

unique_species = penguins['species'].unique()

unique_species

```


unique body masses

```{python}
#| warning: false

body_mass_range = penguins['body_mass_g'].unique()

body_mass_range

```


## data cleaning

first lets remove all rows with either a null species or body_mass_g

```{python}
penguins_clean = penguins.dropna(
    subset=["species", "body_mass_g"]
)

penguins_clean
```

## Average body mass

```{python}
mass_per_species = (
penguins_clean.groupby(by="species").agg(
    {
        "body_mass_g": ["mean"]
    }
     )
)

mass_per_species
```

The table above shows the average body mass for male and female penguins
within each species.

## Body mass by species

```{python}
#| label: fig-body-mass
#| fig-cap: "Average penguin body mass by species."

mass_per_species.plot(kind="bar")
plt.ylabel("Average body mass (g)")
plt.xlabel("Species")
plt.show()
```

The figure shows how the mean body mass of the penguins changes based on thier species and how the Gentoo species has the highest mean body weight
