---
title: "About"
---

## Background

My name is Nitpreet Bamra. I graduated from the University of Waterloo with a degree in Mechatronics engineering in April 2026. I currently attend the University of British Columbia where I am working to get a Master's of Data Science. Aside from school, I like to travel -- with some of my favourite places to visit being Italy, and New York City. My dream travel destination would be to Iceland for where I would travel around the whole country in 5 days going accross thier ring road. Other than that, I like to play alot of sports including : basketball, running, soccer and football. 

## Why data science

I believe that data science is a good intersection between data analytics and software engineering which is what drew me to the field. I have experience working in both data analytics and in machine learning which i feel like gives me the ideal background to continue learning data science. Furthermore, the prospect of building my own machine learning models as well as developing scalable ML ops pipeline is what I aspire to learn/develop in this field. I also feel like data science allows us to automate industry level decision as a scalable level, which is something that I find very inticing.

## Outside of data science

Outside of data science, I like to learn about software engineering and different system design. For example, I like to learn about how many of the worlds most popular software services/products work/operate. For example, one of the projects I find the most interesting is Google maps. I learned that in Google maps they leverage A-star search algorithm which is an algorithm I learned during my undergrad. Beyond this, I like to spend time listening to music, going to museums and reading books
